site_name: Netwrix 1Secure
theme:
  name: readthedocs
  custom_dir: custom_theme
  
nav:
  - Netwrix 1Secure Documentation:
    - Overview: index.md
    - What's New : Whatsnew.md
  - Requirements:
    - Overview: Requirements/README.md
    - Prerequisites for Data Sources: Requirements/PrerequisitesForDataSources.md
    - Netwrix Cloud Agent Requirements: Requirements/CloudAgentRequirements.md
  - Configuration:
    - Overview: Configuration/README.md
    - Active Directory:
      - Active Directory: Configuration/AD/ADManual.md
      - Configure Advanced Audit Policies: Configuration/AD/AdvancedPolicy.md
      - Active Directory automatic configuration: Configuration/AD/Auto.md
      - Active Directory manual configuration: Configuration/AD/CfgManual.md
      - Configure Basic Domain Audit Policies: Configuration/AD/DomainAuditPolicies.md
      - Configure Domain for Monitoring Active Directory: Configuration/AD/ADManual.md
      - Configure Object-Level Auditing: Configuration/AD/ObjectLevel.md
      - Enable Secondary Logon Service: Configuration/AD/SecondaryLogonService.md
      - Group Policy Management Console: Configuration/AD/GroupPolicyManagementConsole.md
      - Protocols and Ports Required for Monitoring Active Directory, Exchange, and Group Policy: Configuration/AD/ProtocolsAndPorts.md
      - Install ADSI Edit: Configuration/AD/ADSI.md
    - Microsoft 365:
      - Registration and Configuration: Configuration/EntraID/RegisterConfig.md
      - Microsoft 365 Permissions: Configuration/EntraID/Permissions.md
    - Logon Activity:
      - Overview: Configuration/LogonActivity/README.md
      - Configure Advanced Audit Policies: Configuration/LogonActivity/AdvancedAudit.md
      - Configure Basic Domain Audit Policies: Configuration/LogonActivity/BasicAuditPolicies.md
      - Configure Windows Firewall Inbound Connection Rules: Configuration/LogonActivity/FirewallRules.md
      - Configure Security Event Log Size and Retention Settings: Configuration/LogonActivity/SecurityLogSize.md
    - Computer:
      - Overview: Configuration/Computer/README.md
      - Protocols and Ports Required for Monitoring File Servers: Configuration/Computer/ProtocolsAndPorts.md
      - Configure Object-Level Access Auditing: Configuration/Computer/ObjectLevel.md
      - Configure Local Audit Policies: Configuration/Computer/LocalPolicy.md
      - Configure Advanced Audit Policies: Configuration/Computer/AdvancedPolicy.md
      - Configure Event Log Size and Retention Settings: Configuration/Computer/EventLog.md
      - Enable Remote Registry Service: Configuration/Computer/RemoteRegistryService.md
      - Configure Windows Firewall Inbound Connection Rules: Configuration/Computer/FirewallRules.md
      - File Servers and Antivirus: Configuration/Computer/FileServersandAntivirus.md
    - SQL Server:
      - Overview: Configuration/SQLServer/README.md
      - SQL Server Ports: Configuration/SQLServer/Ports.md
      - Permissions for SQL Server Auditing: Configuration/SQLServer/Permissions.md
      - Configure Trace Logging: Configuration/SQLServer/ConfiguringTraceLogging.md
    - Configure IT Infrastructure for Auditing and Monitoring: Configuration/ConfigureITInfrastructure.md
    - Settings for Non-Owner Mailbox Access Audit Using Application: Configuration/ExchangeOnlineNonOwner.md
    - NetworkTrafficCompression.htm: Configuration/NetworkTrafficCompression.md
  - Install:
    - Overview: Install/README.md
    - Install Agent : Install/InstallAgent.md
  - Admin:
    - Overview: Admin/README.md
    - 1Secure Dashboard:
      - Overview: Admin/Dashboard/README.md
      - Organization Statistics: Admin/Dashboard/OrganizationStatistics.md
      - Alerts Timeline: Admin/Dashboard/AlertsTimeline.md
    - Organizations:
      - Overview: Admin/Organizations/README.md
      - Sources and Connectors:
        - Overview: Admin/Organizations/SourcesAndConnectors/README.md
        - ActiveDirectory: Admin/Organizations/SourcesAndConnectors/ActiveDirectory.md
        - EntraID: Admin/Organizations/SourcesAndConnectors/EntraID.md
        - Computer: Admin/Organizations/SourcesAndConnectors/Computer.md
        - Exchanage Online: Admin/Organizations/SourcesAndConnectors/ExchangeOnline.md
        - SharePoint Online: Admin/Organizations/SourcesAndConnectors/SharePointOnline.md
        - Add a Source and Connectors for SQL Server: Admin/Organizations/SourcesAndConnectors/SQLServer.md
      - Add Organizations: Admin/Organizations/AddOrganizations.md
      - Manage My Organization: Admin/Organizations/ManageMyOrganization.md
      - Add Sites to Organization: Admin/Organizations/AddSites.md
      - View Tabs of the Organization: Admin/Organizations/ViewTabsAndDashboard.md
      - Billable Accounts: Admin/Organizations/BillableAccounts.md
      - Add Users:
        - Add Users: Admin/Organizations/AddingUsers.md
        - Permissions by Role: Admin/Organizations/RoleDefinitions.md
      - Organization Groups: Admin/Organizations/OrganizationGroups.md
      - Manage Credentials : Admin/Organizations/ManagingCredentials.md
    - Search and Reports:
      - Overview: Admin/SearchAndReports/README.md
      - Activity Reports: Admin/SearchAndReports/Activity.md
      - Compliance Reports: Admin/SearchAndReports/Compliance.md
      - State In Time Risks Reports: Admin/SearchAndReports/StateInTime.md
      - System Reports: Admin/SearchAndReports/System.md
      - Custom Reports: Admin/SearchAndReports/CustomReports.md
      - Audit Logs: Admin/SearchAndReports/AuditLogs.md
      - Export a Report or Investigation Results: Admin/SearchAndReports/ExportReport.md
      - Subscriptions: Admin/SearchAndReports/Subscriptions.md
      - Apply Filters: Admin/SearchAndReports/ApplyFilters.md
      - Filter operators: Admin/SearchAndReports/FilterOperators.md
      - Billable Users: Admin/SearchAndReports/BillableUsers.md
    - Data Collection:
      - Overview: Admin/DataCollection/README.md
      - Data Collecting Account: Admin/DataCollection/DataCollectingAccount/README.md
      - Microsoft Entra ID Auditing: Admin/DataCollection/EntraID.md
      - SharePoint Online Auditing: Admin/DataCollection/SharePointOnline.md
      - Exchange Online Auditing: Admin/DataCollection/ExchangeOnline.md
      - Active Directory:
        - Active Directory: Admin/DataCollection/ActiveDirectory/ActiveDirectoryAuditing.md
        - AuditLogsRole.htm: Admin/DataCollection/ActiveDirectory/AuditLogsRole.md
        - PermissionsADContainer.htm: Admin/DataCollection/ActiveDirectory/PermissionsADContainer.md
        - ManageAuditingSecurityLog.htm: Admin/DataCollection/ActiveDirectory/ManageAuditingSecurityLog.md
        - PermissionsRegistryKeys.htm: Admin/DataCollection/ActiveDirectory/PermissionsRegistryKeys.md
        - Define Log On As a Batch Job Policy: Admin/DataCollection/ActiveDirectory/LogOnAsBatch.md
        - AuditLogging.htm: Admin/DataCollection/ActiveDirectory/AuditLogging.md
      - Computer:
        - Computer: Admin/DataCollection/Computer/README.md
        - Configure the Back up Files and Directories Policy: Admin/DataCollection/Computer/BackupFilesDirectories.md
      - Logon Activity:
        - Logon Activity: Admin/DataCollection/LogonActivity/README.md
        - Configure Non-Administrative Account to Collect Logon Activity : Admin/DataCollection/LogonActivity/NonDomainAdmin.md
      - GMSA: Admin/DataCollection/GMSA/GMSA.md
    - Risk Profiles:
      - Overview: Admin/RiskProfiles/README.md
      - Configure Risk Profile: Admin/RiskProfiles/ConfigureProfile.md
      - Review Risks using Risks Assessment Dashboard: Admin/RiskProfiles/RiskAssessmentDashboard.md
      - Risk Profiles: Admin/RiskProfiles/AddProfile.md
    - Alert Profiles:
      - Overview: Admin/Alerts/README.md
      - Alerts: Admin/Alerts/Alerts.md
    - Log in : Admin/LogIn.md
    - Statuses : Admin/Statuses.md
    - Notifications : Admin/Notifications.md
    - Update Netwrix Cloud Agent: Admin/UpdateNetwrixCloudAgent.md
    -  How it works: Admin/HowItWorks.md
  - Integration:
    - Overview: Integration/README.md
    - ConnectWise: Integration/ConnectWise.md
    - ServiceNow: Integration/ServiceNow.md
    - SharePoint Online: Integration/SharePointOnline.md
  - Security:
    - Overview: Security/README.md
    - Compliance: Security/Compliance.md
    - Customer Data Privacy: Security/CustomerDataPrivacy.md
    - Access Control: Security/AccessControl.md
    - Data Security: Security/DataSecurity.md

plugins: 
  - search
  - markdownextradata
  - snippets
extra_css:
  - css/netwrix.css