DirectoryReadAll: |-
  @@@NEEDSCONVERSION@@@

AuditLogReadAll: |-
  @@@NEEDSCONVERSION@@@

PolicyReadAll: |-
  @@@NEEDSCONVERSION@@@

SitesReadAll: |-
  @@@NEEDSCONVERSION@@@

SitesReadWriteAll: |-
  @@@NEEDSCONVERSION@@@
